import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/navigation";
import { ClerkProvider } from "@clerk/nextjs";
import { StoreProvider } from "@/store/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <StoreProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            <header>
              <NavigationBar />
            </header>

            <main className='flex justify-center mt-2 mb-2'>
              {children}
            </main>

            <footer className='flex justify-center items-center w-full h-[7.5vh] border-t-2 border-gray-200'>
              <h1 className='text-sm md:text-md italic'>@2025 Software Requirements App All Rights Reserved</h1>
            </footer>
          </body>
        </html>
      </StoreProvider>
    </ClerkProvider>
  );
}
